name: 'Pull request comments from clang-tidy reports'
description: 'Post clang-tidy warnings as review comments on pull requests'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  clang_tidy_fixes:
    description: 'Path to the clang-tidy fixes YAML file'
    required: true
  request_changes:
    description: 'Request changes if there are clang-tidy issues (otherwise leave a comment)'
    default: false
  suggestions_per_comment:
    description: 'The number of suggestions per comment (smaller numbers work better for heavy pull requests)'
    default: 10
  repository_root:
    description: 'The root directory of the respository'
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - run: pip3 install -r  ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_CLANG_TIDY_FIXES: ${{ inputs.clang_tidy_fixes }}
        INPUT_REQUEST_CHANGES: ${{ inputs.request_changes }}
        INPUT_SUGGESTIONS_PER_COMMENT: ${{ inputs.suggestions_per_comment }}
        INPUT_REPOSITORY_ROOT: ${{ inputs.repository_root }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        PYTHON_SCRIPT_PATH: ${{ github.action_path }}
    
    
